### ISSUE TITLE
config.py and loss_functions.py files are missing

### ISSUE THREAD

**Issue by dyqq03** [NavidFeizi/DeepKoopman_catheter_model#1]
Sorry sir, I didn't find the config.py and loss_functions.py files, how should I solve it.

**Comment by NavidFeizi** [comment]
Oh, thanks for raising this issue. It was a mistake from my side. I have updated the repo, and it should be fixed. Also, you can look at our IEEE RAL paper in the References section for more details.

**Comment by hoangphuckhanh005-dot** [comment]
Sorry sir, I still can't find the config.py and loss_functions.py files when downloading, even after updating.
